/*
 * Calendar Service
 *
 * Copyright (c) 2012 - 2013 Samsung Electronics Co., Ltd. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
#ifndef __CALENDAR_SVC_VIEW_H__
#define __CALENDAR_SVC_VIEW_H__

#include "calendar_view.h"

_CALENDAR_BEGIN_VIEW()
    _CALENDAR_PROPERTY_INT( event_id )
    _CALENDAR_PROPERTY_CALTIME( start_time )
    _CALENDAR_PROPERTY_CALTIME( end_time )
    _CALENDAR_PROPERTY_STR( summary )
    _CALENDAR_PROPERTY_STR( location )
    _CALENDAR_PROPERTY_INT( calendar_book_id )
    _CALENDAR_PROPERTY_STR( description )
    _CALENDAR_PROPERTY_INT( busy_status )
    _CALENDAR_PROPERTY_INT( event_status )
    _CALENDAR_PROPERTY_INT( priority )
    _CALENDAR_PROPERTY_INT( sensitivity )
    _CALENDAR_PROPERTY_INT( has_rrule )
    _CALENDAR_PROPERTY_DOUBLE( latitude )
    _CALENDAR_PROPERTY_DOUBLE( longitude )
    _CALENDAR_PROPERTY_INT( has_alarm )
    _CALENDAR_PROPERTY_INT( original_event_id )
    _CALENDAR_PROPERTY_LLI( last_modified_time )
_CALENDAR_END_VIEW( _calendar_instance_normal )    // read_only

_CALENDAR_BEGIN_VIEW()
    _CALENDAR_PROPERTY_INT( event_id )
    _CALENDAR_PROPERTY_CALTIME( start_time )
    _CALENDAR_PROPERTY_CALTIME( end_time )
    _CALENDAR_PROPERTY_STR( summary )
    _CALENDAR_PROPERTY_STR( location )
    _CALENDAR_PROPERTY_INT( calendar_book_id )
    _CALENDAR_PROPERTY_STR( description )
    _CALENDAR_PROPERTY_INT( busy_status )
    _CALENDAR_PROPERTY_INT( event_status )
    _CALENDAR_PROPERTY_INT( priority )
    _CALENDAR_PROPERTY_INT( sensitivity )
    _CALENDAR_PROPERTY_INT( has_rrule )
    _CALENDAR_PROPERTY_DOUBLE( latitude )
    _CALENDAR_PROPERTY_DOUBLE( longitude )
    _CALENDAR_PROPERTY_INT( has_alarm )
    _CALENDAR_PROPERTY_INT( original_event_id )
    _CALENDAR_PROPERTY_LLI( last_modified_time )
_CALENDAR_END_VIEW( _calendar_instance_allday )    // read_only

// db record view // get, get_list, insert, update, delete, filter
#define CALENDAR_VIEW_CALENDAR              "tizen.calendar_view.calendar"
#define CALENDAR_VIEW_EVENT                 "tizen.calendar_view.event"
#define CALENDAR_VIEW_TODO                  "tizen.calendar_view.todo"
#define CALENDAR_VIEW_TIMEZONE              "tizen.calendar_view.timezone"
// child view
#define CALENDAR_VIEW_ATTENDEE              "tizen.calendar_view.attendee"
#define CALENDAR_VIEW_ALARM                 "tizen.calendar_view.alarm"

// logical view  // get_list, filter
#define CALENDAR_VIEW_INSTANCE_NORMAL       "tizen.calendar_view.instance_normal"
#define CALENDAR_VIEW_INSTANCE_ALLDAY       "tizen.calendar_view.instance_allday"

// updated info  // get_list
#define CALENDAR_VIEW_UPDATED_INFO          "tizen.calendar_view.updated_info"

// extended_table
#define CALENDAR_VIEW_EXTENDED              "tizen,calendar_view.extended_property"

// only for query (filter)
#define CALENDAR_VIEW_EVENT_CALENDAR             "tizen.calendar_view.event/calendar"
#define CALENDAR_VIEW_TODO_CALENDAR             "tizen.calendar_view.todo/calendar"
#define CALENDAR_VIEW_EVENT_CALENDAR_ATTENDEE    "tizen.calendar_view.event/calendar/attendee"
#define CALENDAR_VIEW_INSTANCE_NORMAL_CALENDAR   "tizen.calendar_view.instance_normal/calendar"
#define CALENDAR_VIEW_INSTANCE_ALLDAY_CALENDAR   "tizen.calendar_view.instance_allday/calendar"

// for type check         // data_type mask 0x000FF000
#define CAL_PROPERTY_DATA_TYPE_MASK             0x000FF000
#define CAL_PROPERTY_DATA_TYPE_INT              0x00001000
#define CAL_PROPERTY_DATA_TYPE_STR              0x00002000
#define CAL_PROPERTY_DATA_TYPE_DOUBLE           0x00003000
#define CAL_PROPERTY_DATA_TYPE_LLI              0x00004000
#define CAL_PROPERTY_DATA_TYPE_CALTIME          0x00005000
#define CAL_PROPERTY_DATA_TYPE_REC              0x00006000
#define CAL_PROPERTY_CHECK_DATA_TYPE(property_id,data_type) \
    ((property_id&CAL_PROPERTY_DATA_TYPE_MASK) == data_type ? true : false)
// for property                             //  0xFF000000
#define CAL_PROPERTY_MASK                       0xFF000000
#define CAL_PROPERTY_CALENDAR                   0x01000000
#define CAL_PROPERTY_EVENT                      0x02000000
#define CAL_PROPERTY_TODO                       0x03000000
#define CAL_PROPERTY_TIMEZONE                   0x04000000
#define CAL_PROPERTY_ATTENDEE                   0x05000000
#define CAL_PROPERTY_ALARM                      0x06000000
#define CAL_PROPERTY_INSTANCE_NORMAL            0x07000000
#define CAL_PROPERTY_INSTANCE_ALLDAY            0x08000000
#define CAL_PROPERTY_UPDATED_INFO               0x09000000
#define CAL_PROPERTY_EXTENDED                   0x0A000000
#define CAL_PROPERTY_CHECK(property_id,data_type) \
    ((property_id&CAL_PROPERTY_MASK) == data_type ? true : false)

#define CAL_PROPERTY_FLAGS_MASK                 0x00F00000
#define CAL_PROPERTY_FLAGS_FILTER               0x00100000
#define CAL_PROPERTY_FLAGS_PROJECTION           0x00200000
#define CAL_PROPERTY_FLAGS_READ_ONLY            0x00300000
#define CAL_PROPERTY_CHECK_FLAGS(property_id,data_type) \
    ((property_id&CAL_PROPERTY_FLAGS_MASK) == data_type ? true : false)

typedef enum {
	CAL_PROPERTY_CALENDAR_ID                = (CAL_PROPERTY_CALENDAR|CAL_PROPERTY_DATA_TYPE_INT|CAL_PROPERTY_FLAGS_READ_ONLY),
	CAL_PROPERTY_CALENDAR_UID               = (CAL_PROPERTY_CALENDAR|CAL_PROPERTY_DATA_TYPE_STR) +1,
	CAL_PROPERTY_CALENDAR_NAME              = (CAL_PROPERTY_CALENDAR|CAL_PROPERTY_DATA_TYPE_STR) +2,
	CAL_PROPERTY_CALENDAR_DESCRIPTION       = (CAL_PROPERTY_CALENDAR|CAL_PROPERTY_DATA_TYPE_STR) +3,
	CAL_PROPERTY_CALENDAR_COLOR             = (CAL_PROPERTY_CALENDAR|CAL_PROPERTY_DATA_TYPE_STR) +4,
	CAL_PROPERTY_CALENDAR_LOCATION          = (CAL_PROPERTY_CALENDAR|CAL_PROPERTY_DATA_TYPE_STR) +5,
	CAL_PROPERTY_CALENDAR_VISIBILITY        = (CAL_PROPERTY_CALENDAR|CAL_PROPERTY_DATA_TYPE_INT) +6,
	CAL_PROPERTY_CALENDAR_SYNC_EVENT        = (CAL_PROPERTY_CALENDAR|CAL_PROPERTY_DATA_TYPE_INT) +7,
	CAL_PROPERTY_CALENDAR_IS_DELETED        = (CAL_PROPERTY_CALENDAR|CAL_PROPERTY_DATA_TYPE_INT) +8,
	CAL_PROPERTY_CALENDAR_ACCOUNT_ID        = (CAL_PROPERTY_CALENDAR|CAL_PROPERTY_DATA_TYPE_INT) +9,
	CAL_PROPERTY_CALENDAR_STORE_TYPE        = (CAL_PROPERTY_CALENDAR|CAL_PROPERTY_DATA_TYPE_INT) +10,
	CAL_PROPERTY_CALENDAR_SYNC_DATA1        = (CAL_PROPERTY_CALENDAR|CAL_PROPERTY_DATA_TYPE_STR) +11,
	CAL_PROPERTY_CALENDAR_SYNC_DATA2        = (CAL_PROPERTY_CALENDAR|CAL_PROPERTY_DATA_TYPE_STR) +12,
	CAL_PROPERTY_CALENDAR_SYNC_DATA3        = (CAL_PROPERTY_CALENDAR|CAL_PROPERTY_DATA_TYPE_STR) +13,
	CAL_PROPERTY_CALENDAR_SYNC_DATA4        = (CAL_PROPERTY_CALENDAR|CAL_PROPERTY_DATA_TYPE_STR) +14,

	CAL_PROPERTY_EVENT_ID                   = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT|CAL_PROPERTY_FLAGS_READ_ONLY),
	CAL_PROPERTY_EVENT_CALENDAR_ID          = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT) +1,
	CAL_PROPERTY_EVENT_SUMMARY              = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +2,
	CAL_PROPERTY_EVENT_DESCRIPTION          = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +3,
	CAL_PROPERTY_EVENT_LOCATION             = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +4,
	CAL_PROPERTY_EVENT_CATEGORIES           = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +5,
	CAL_PROPERTY_EVENT_EXDATE               = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +6,
	CAL_PROPERTY_EVENT_EVENT_STATUS         = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT) +7,
	CAL_PROPERTY_EVENT_PRIORITY             = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT) +8,
	CAL_PROPERTY_EVENT_TIMEZONE             = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT) +9,
	CAL_PROPERTY_EVENT_CONTACT_ID           = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT) +10,
	CAL_PROPERTY_EVENT_BUSY_STATUS          = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT) +11,
	CAL_PROPERTY_EVENT_SENSITIVITY          = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT) +12,
	CAL_PROPERTY_EVENT_UID                  = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +13,
	CAL_PROPERTY_EVENT_ORGANIZER_NAME       = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +14,
	CAL_PROPERTY_EVENT_ORGANIZER_EMAIL      = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +15,
	CAL_PROPERTY_EVENT_MEETING_STATUS       = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT) +16,
	CAL_PROPERTY_EVENT_ORIGINAL_EVENT_ID    = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT) +17,
	CAL_PROPERTY_EVENT_LATITUDE             = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_DOUBLE) +18,
	CAL_PROPERTY_EVENT_LONGITUDE            = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_DOUBLE) +19,
	CAL_PROPERTY_EVENT_EMAIL_ID             = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT) +20,
	CAL_PROPERTY_EVENT_CREATED_TIME         = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_LLI) +21,
	CAL_PROPERTY_EVENT_LAST_MODIFIED_TIME   = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_LLI) +22,
	CAL_PROPERTY_EVENT_IS_DELETED           = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT|CAL_PROPERTY_FLAGS_READ_ONLY) +23,
	CAL_PROPERTY_EVENT_FREQ                 = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT) +24,
	CAL_PROPERTY_EVENT_RANGE_TYPE           = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT) +25,
	CAL_PROPERTY_EVENT_UNTIL                = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_CALTIME) +26,
	CAL_PROPERTY_EVENT_COUNT                = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT) +27,
	CAL_PROPERTY_EVENT_INTERVAL             = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT) +28,
	CAL_PROPERTY_EVENT_BYSECOND             = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +29,
	CAL_PROPERTY_EVENT_BYMINUTE             = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +30,
	CAL_PROPERTY_EVENT_BYHOUR               = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +31,
	CAL_PROPERTY_EVENT_BYDAY                = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +32,
	CAL_PROPERTY_EVENT_BYMONTHDAY           = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +33,
	CAL_PROPERTY_EVENT_BYYEARDAY            = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +34,
	CAL_PROPERTY_EVENT_BYWEEKNO             = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +35,
	CAL_PROPERTY_EVENT_BYMONTH              = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +36,
	CAL_PROPERTY_EVENT_BYSETPOS             = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +37,
	CAL_PROPERTY_EVENT_WKST                 = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT) +38,
	CAL_PROPERTY_EVENT_RECURRENCE_ID        = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +39,
	CAL_PROPERTY_EVENT_RDATE                = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +40,
	CAL_PROPERTY_EVENT_HAS_ATTENDEE         = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT|CAL_PROPERTY_FLAGS_READ_ONLY) +41,
	CAL_PROPERTY_EVENT_HAS_ALARM            = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT|CAL_PROPERTY_FLAGS_READ_ONLY) +42,
	CAL_PROPERTY_EVENT_SYNC_DATA1           = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +43,
	CAL_PROPERTY_EVENT_SYNC_DATA2           = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +44,
	CAL_PROPERTY_EVENT_SYNC_DATA3           = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +45,
	CAL_PROPERTY_EVENT_SYNC_DATA4           = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +46,
	CAL_PROPERTY_EVENT_START                = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_CALTIME) +47,
	CAL_PROPERTY_EVENT_END                  = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_CALTIME) +48,
	CAL_PROPERTY_EVENT_CALENDAR_ALARM       = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_REC) +49,
	CAL_PROPERTY_EVENT_CALENDAR_ATTENDEE    = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_REC) +50,
    CAL_PROPERTY_EVENT_CALENDAR_SYSTEM_TYPE = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT) +51,
    CAL_PROPERTY_EVENT_START_TZID           = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +52,
    CAL_PROPERTY_EVENT_END_TZID             = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_STR) +53,
    CAL_PROPERTY_EVENT_EXCEPTION            = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_REC) +54,
    CAL_PROPERTY_EVENT_EXTENDED             = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_REC) +55,
    CAL_PROPERTY_EVENT_IS_ALLDAY            = (CAL_PROPERTY_EVENT|CAL_PROPERTY_DATA_TYPE_INT|CAL_PROPERTY_FLAGS_READ_ONLY) +56,

	CAL_PROPERTY_TODO_ID                    =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_INT|CAL_PROPERTY_FLAGS_READ_ONLY),
	CAL_PROPERTY_TODO_CALENDAR_ID           =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_INT) +1,
	CAL_PROPERTY_TODO_SUMMARY               =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +2,
	CAL_PROPERTY_TODO_DESCRIPTION           =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +3,
	CAL_PROPERTY_TODO_LOCATION              =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +4,
	CAL_PROPERTY_TODO_CATEGORIES            =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +5,
	CAL_PROPERTY_TODO_TODO_STATUS           =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_INT) +6,
	CAL_PROPERTY_TODO_PRIORITY              =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_INT) +7,
	CAL_PROPERTY_TODO_SENSITIVITY           =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_INT) +8,
	CAL_PROPERTY_TODO_UID                   =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +9,
	CAL_PROPERTY_TODO_LATITUDE              =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_DOUBLE) +10,
	CAL_PROPERTY_TODO_LONGITUDE             =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_DOUBLE) +11,
	CAL_PROPERTY_TODO_PROGRESS              =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_INT) +12,
	CAL_PROPERTY_TODO_CREATED_TIME          =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_LLI) +13,
	CAL_PROPERTY_TODO_LAST_MODIFIED_TIME    =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_LLI) +14,
	CAL_PROPERTY_TODO_COMPLETED_TIME        =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_LLI) +15,
	CAL_PROPERTY_TODO_IS_DELETED            =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_INT|CAL_PROPERTY_FLAGS_READ_ONLY) +16,
	CAL_PROPERTY_TODO_FREQ                  =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_INT) +17,
	CAL_PROPERTY_TODO_RANGE_TYPE            =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_INT) +18,
	CAL_PROPERTY_TODO_UNTIL                 =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_CALTIME) +19,
	CAL_PROPERTY_TODO_COUNT                 =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_INT) +20,
	CAL_PROPERTY_TODO_INTERVAL              =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_INT) +21,
	CAL_PROPERTY_TODO_BYSECOND              =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +22,
	CAL_PROPERTY_TODO_BYMINUTE              =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +23,
	CAL_PROPERTY_TODO_BYHOUR                =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +24,
	CAL_PROPERTY_TODO_BYDAY                 =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +25,
	CAL_PROPERTY_TODO_BYMONTHDAY            =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +26,
	CAL_PROPERTY_TODO_BYYEARDAY             =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +27,
	CAL_PROPERTY_TODO_BYWEEKNO              =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +28,
	CAL_PROPERTY_TODO_BYMONTH               =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +29,
	CAL_PROPERTY_TODO_BYSETPOS              =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +30,
	CAL_PROPERTY_TODO_WKST                  =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_INT) +31,
	CAL_PROPERTY_TODO_HAS_ALARM             =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_INT|CAL_PROPERTY_FLAGS_READ_ONLY) +32,
	CAL_PROPERTY_TODO_SYNC_DATA1            =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +33,
	CAL_PROPERTY_TODO_SYNC_DATA2            =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +34,
	CAL_PROPERTY_TODO_SYNC_DATA3            =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +35,
	CAL_PROPERTY_TODO_SYNC_DATA4            =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +36,
	CAL_PROPERTY_TODO_START                 =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_CALTIME) +37,
	CAL_PROPERTY_TODO_DUE                   =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_CALTIME) +38,
	CAL_PROPERTY_TODO_CALENDAR_ALARM        =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_REC) +39,
    CAL_PROPERTY_TODO_START_TZID            =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +40,
    CAL_PROPERTY_TODO_DUE_TZID              =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +41,
    CAL_PROPERTY_TODO_ORGANIZER_NAME        =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +42,
    CAL_PROPERTY_TODO_ORGANIZER_EMAIL       =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_STR) +43,
    CAL_PROPERTY_TODO_HAS_ATTENDEE          =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_INT|CAL_PROPERTY_FLAGS_READ_ONLY) +44,
    CAL_PROPERTY_TODO_CALENDAR_ATTENDEE     =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_REC) +45,
    CAL_PROPERTY_TODO_EXTENDED              =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_REC) +46,
    CAL_PROPERTY_TODO_IS_ALLDAY             =(CAL_PROPERTY_TODO|CAL_PROPERTY_DATA_TYPE_INT|CAL_PROPERTY_FLAGS_READ_ONLY) +47,

	CAL_PROPERTY_TIMEZONE_ID								=(CAL_PROPERTY_TIMEZONE|CAL_PROPERTY_DATA_TYPE_INT|CAL_PROPERTY_FLAGS_READ_ONLY),
	CAL_PROPERTY_TIMEZONE_TZ_OFFSET_FROM_GMT                =(CAL_PROPERTY_TIMEZONE|CAL_PROPERTY_DATA_TYPE_INT)+1,
	CAL_PROPERTY_TIMEZONE_STANDARD_NAME                     =(CAL_PROPERTY_TIMEZONE|CAL_PROPERTY_DATA_TYPE_STR)+2,
	CAL_PROPERTY_TIMEZONE_STD_START_MONTH                   =(CAL_PROPERTY_TIMEZONE|CAL_PROPERTY_DATA_TYPE_INT)+3,
	CAL_PROPERTY_TIMEZONE_STD_START_POSITION_OF_WEEK        =(CAL_PROPERTY_TIMEZONE|CAL_PROPERTY_DATA_TYPE_INT)+4,
	CAL_PROPERTY_TIMEZONE_STD_START_DAY                     =(CAL_PROPERTY_TIMEZONE|CAL_PROPERTY_DATA_TYPE_INT)+5,
	CAL_PROPERTY_TIMEZONE_STD_START_HOUR                    =(CAL_PROPERTY_TIMEZONE|CAL_PROPERTY_DATA_TYPE_INT)+6,
	CAL_PROPERTY_TIMEZONE_STANDARD_BIAS                     =(CAL_PROPERTY_TIMEZONE|CAL_PROPERTY_DATA_TYPE_INT)+7,
	CAL_PROPERTY_TIMEZONE_DAY_LIGHT_NAME                    =(CAL_PROPERTY_TIMEZONE|CAL_PROPERTY_DATA_TYPE_STR)+8,
	CAL_PROPERTY_TIMEZONE_DAY_LIGHT_START_MONTH             =(CAL_PROPERTY_TIMEZONE|CAL_PROPERTY_DATA_TYPE_INT)+9,
	CAL_PROPERTY_TIMEZONE_DAY_LIGHT_START_POSITION_OF_WEEK  =(CAL_PROPERTY_TIMEZONE|CAL_PROPERTY_DATA_TYPE_INT)+10,
	CAL_PROPERTY_TIMEZONE_DAY_LIGHT_START_DAY               =(CAL_PROPERTY_TIMEZONE|CAL_PROPERTY_DATA_TYPE_INT)+11,
	CAL_PROPERTY_TIMEZONE_DAY_LIGHT_START_HOUR              =(CAL_PROPERTY_TIMEZONE|CAL_PROPERTY_DATA_TYPE_INT)+12,
	CAL_PROPERTY_TIMEZONE_DAY_LIGHT_BIAS                    =(CAL_PROPERTY_TIMEZONE|CAL_PROPERTY_DATA_TYPE_INT)+13,
	CAL_PROPERTY_TIMEZONE_CALENDAR_ID                       =(CAL_PROPERTY_TIMEZONE|CAL_PROPERTY_DATA_TYPE_INT)+14,


	CAL_PROPERTY_ATTENDEE_NUMBER            =(CAL_PROPERTY_ATTENDEE|CAL_PROPERTY_DATA_TYPE_STR),
	CAL_PROPERTY_ATTENDEE_TYPE              =(CAL_PROPERTY_ATTENDEE|CAL_PROPERTY_DATA_TYPE_INT)+1,
	CAL_PROPERTY_ATTENDEE_CT_INDEX          =(CAL_PROPERTY_ATTENDEE|CAL_PROPERTY_DATA_TYPE_INT)+2,
	CAL_PROPERTY_ATTENDEE_UID               =(CAL_PROPERTY_ATTENDEE|CAL_PROPERTY_DATA_TYPE_STR)+3,
	CAL_PROPERTY_ATTENDEE_GROUP             =(CAL_PROPERTY_ATTENDEE|CAL_PROPERTY_DATA_TYPE_STR)+4,
	CAL_PROPERTY_ATTENDEE_EMAIL             =(CAL_PROPERTY_ATTENDEE|CAL_PROPERTY_DATA_TYPE_STR)+5,
	CAL_PROPERTY_ATTENDEE_ROLE              =(CAL_PROPERTY_ATTENDEE|CAL_PROPERTY_DATA_TYPE_INT)+6,
	CAL_PROPERTY_ATTENDEE_STATUS            =(CAL_PROPERTY_ATTENDEE|CAL_PROPERTY_DATA_TYPE_INT)+7,
	CAL_PROPERTY_ATTENDEE_RSVP              =(CAL_PROPERTY_ATTENDEE|CAL_PROPERTY_DATA_TYPE_INT)+8,
	CAL_PROPERTY_ATTENDEE_DELEGATE_URI      =(CAL_PROPERTY_ATTENDEE|CAL_PROPERTY_DATA_TYPE_STR)+9,
	CAL_PROPERTY_ATTENDEE_DELEGATOR_URI     =(CAL_PROPERTY_ATTENDEE|CAL_PROPERTY_DATA_TYPE_STR)+10,
	CAL_PROPERTY_ATTENDEE_NAME              =(CAL_PROPERTY_ATTENDEE|CAL_PROPERTY_DATA_TYPE_STR)+11,
	CAL_PROPERTY_ATTENDEE_EVENT_ID          =(CAL_PROPERTY_ATTENDEE|CAL_PROPERTY_DATA_TYPE_INT)+12,

	CAL_PROPERTY_ALARM_TYPE                 =(CAL_PROPERTY_ALARM|CAL_PROPERTY_DATA_TYPE_INT),
	CAL_PROPERTY_ALARM_TIME                 =(CAL_PROPERTY_ALARM|CAL_PROPERTY_DATA_TYPE_LLI)+1,
	CAL_PROPERTY_ALARM_TICK                 =(CAL_PROPERTY_ALARM|CAL_PROPERTY_DATA_TYPE_INT)+2,
	CAL_PROPERTY_ALARM_TICK_UNIT            =(CAL_PROPERTY_ALARM|CAL_PROPERTY_DATA_TYPE_INT)+3,
	CAL_PROPERTY_ALARM_TONE                 =(CAL_PROPERTY_ALARM|CAL_PROPERTY_DATA_TYPE_STR)+4,
	CAL_PROPERTY_ALARM_DESCRIPTION          =(CAL_PROPERTY_ALARM|CAL_PROPERTY_DATA_TYPE_STR)+5,
	CAL_PROPERTY_ALARM_ID                   =(CAL_PROPERTY_ALARM|CAL_PROPERTY_DATA_TYPE_INT)+6,
	CAL_PROPERTY_ALARM_EVENT_TODO_ID        =(CAL_PROPERTY_ALARM|CAL_PROPERTY_DATA_TYPE_INT)+7,

    CAL_PROPERTY_INSTANCE_NORMAL_EVENT_ID       =(CAL_PROPERTY_INSTANCE_NORMAL|CAL_PROPERTY_DATA_TYPE_INT),
	CAL_PROPERTY_INSTANCE_NORMAL_START          =(CAL_PROPERTY_INSTANCE_NORMAL|CAL_PROPERTY_DATA_TYPE_CALTIME) +1,
	CAL_PROPERTY_INSTANCE_NORMAL_END            =(CAL_PROPERTY_INSTANCE_NORMAL|CAL_PROPERTY_DATA_TYPE_CALTIME) +2,
	CAL_PROPERTY_INSTANCE_NORMAL_SUMMARY        =(CAL_PROPERTY_INSTANCE_NORMAL|CAL_PROPERTY_DATA_TYPE_STR)+3,
	CAL_PROPERTY_INSTANCE_NORMAL_LOCATION       =(CAL_PROPERTY_INSTANCE_NORMAL|CAL_PROPERTY_DATA_TYPE_STR)+4,
	CAL_PROPERTY_INSTANCE_NORMAL_CALENDAR_ID    =(CAL_PROPERTY_INSTANCE_NORMAL|CAL_PROPERTY_DATA_TYPE_INT)+5,
	CAL_PROPERTY_INSTANCE_NORMAL_DESCRIPTION    =(CAL_PROPERTY_INSTANCE_NORMAL|CAL_PROPERTY_DATA_TYPE_STR)+6,
	CAL_PROPERTY_INSTANCE_NORMAL_BUSY_STATUS    =(CAL_PROPERTY_INSTANCE_NORMAL|CAL_PROPERTY_DATA_TYPE_INT)+7,
	CAL_PROPERTY_INSTANCE_NORMAL_EVENT_STATUS   =(CAL_PROPERTY_INSTANCE_NORMAL|CAL_PROPERTY_DATA_TYPE_INT)+8,
	CAL_PROPERTY_INSTANCE_NORMAL_PRIORITY       =(CAL_PROPERTY_INSTANCE_NORMAL|CAL_PROPERTY_DATA_TYPE_INT)+9,
	CAL_PROPERTY_INSTANCE_NORMAL_SENSITIVITY    =(CAL_PROPERTY_INSTANCE_NORMAL|CAL_PROPERTY_DATA_TYPE_INT)+10,
	CAL_PROPERTY_INSTANCE_NORMAL_HAS_RRULE      =(CAL_PROPERTY_INSTANCE_NORMAL|CAL_PROPERTY_DATA_TYPE_INT)+11,
	CAL_PROPERTY_INSTANCE_NORMAL_LATITUDE       =(CAL_PROPERTY_INSTANCE_NORMAL|CAL_PROPERTY_DATA_TYPE_DOUBLE)+12,
	CAL_PROPERTY_INSTANCE_NORMAL_LONGITUDE      =(CAL_PROPERTY_INSTANCE_NORMAL|CAL_PROPERTY_DATA_TYPE_DOUBLE)+13,
	CAL_PROPERTY_INSTANCE_NORMAL_HAS_ALARM      =(CAL_PROPERTY_INSTANCE_NORMAL|CAL_PROPERTY_DATA_TYPE_INT)+14,
	CAL_PROPERTY_INSTANCE_NORMAL_ORIGINAL_EVENT_ID  =(CAL_PROPERTY_INSTANCE_NORMAL|CAL_PROPERTY_DATA_TYPE_INT)+15,
	CAL_PROPERTY_INSTANCE_NORMAL_LAST_MODIFIED_TIME =(CAL_PROPERTY_INSTANCE_NORMAL|CAL_PROPERTY_DATA_TYPE_LLI)+16,

    CAL_PROPERTY_INSTANCE_ALLDAY_EVENT_ID       =(CAL_PROPERTY_INSTANCE_NORMAL|CAL_PROPERTY_DATA_TYPE_INT),
	CAL_PROPERTY_INSTANCE_ALLDAY_START          =(CAL_PROPERTY_INSTANCE_ALLDAY|CAL_PROPERTY_DATA_TYPE_CALTIME) +1,
    CAL_PROPERTY_INSTANCE_ALLDAY_END            =(CAL_PROPERTY_INSTANCE_ALLDAY|CAL_PROPERTY_DATA_TYPE_CALTIME) +2,
	CAL_PROPERTY_INSTANCE_ALLDAY_SUMMARY        =(CAL_PROPERTY_INSTANCE_ALLDAY|CAL_PROPERTY_DATA_TYPE_STR)+3,
	CAL_PROPERTY_INSTANCE_ALLDAY_LOCATION       =(CAL_PROPERTY_INSTANCE_ALLDAY|CAL_PROPERTY_DATA_TYPE_STR)+4,
	CAL_PROPERTY_INSTANCE_ALLDAY_CALENDAR_ID    =(CAL_PROPERTY_INSTANCE_ALLDAY|CAL_PROPERTY_DATA_TYPE_INT)+5,
	CAL_PROPERTY_INSTANCE_ALLDAY_DESCRIPTION    =(CAL_PROPERTY_INSTANCE_ALLDAY|CAL_PROPERTY_DATA_TYPE_STR)+6,
	CAL_PROPERTY_INSTANCE_ALLDAY_BUSY_STATUS    =(CAL_PROPERTY_INSTANCE_ALLDAY|CAL_PROPERTY_DATA_TYPE_INT)+7,
	CAL_PROPERTY_INSTANCE_ALLDAY_EVENT_STATUS   =(CAL_PROPERTY_INSTANCE_ALLDAY|CAL_PROPERTY_DATA_TYPE_INT)+8,
	CAL_PROPERTY_INSTANCE_ALLDAY_PRIORITY       =(CAL_PROPERTY_INSTANCE_ALLDAY|CAL_PROPERTY_DATA_TYPE_INT)+9,
	CAL_PROPERTY_INSTANCE_ALLDAY_SENSITIVITY    =(CAL_PROPERTY_INSTANCE_ALLDAY|CAL_PROPERTY_DATA_TYPE_INT)+10,
	CAL_PROPERTY_INSTANCE_ALLDAY_HAS_RRULE      =(CAL_PROPERTY_INSTANCE_ALLDAY|CAL_PROPERTY_DATA_TYPE_INT)+11,
	CAL_PROPERTY_INSTANCE_ALLDAY_LATITUDE       =(CAL_PROPERTY_INSTANCE_ALLDAY|CAL_PROPERTY_DATA_TYPE_DOUBLE)+12,
	CAL_PROPERTY_INSTANCE_ALLDAY_LONGITUDE      =(CAL_PROPERTY_INSTANCE_ALLDAY|CAL_PROPERTY_DATA_TYPE_DOUBLE)+13,
	CAL_PROPERTY_INSTANCE_ALLDAY_HAS_ALARM      =(CAL_PROPERTY_INSTANCE_ALLDAY|CAL_PROPERTY_DATA_TYPE_INT)+14,
	CAL_PROPERTY_INSTANCE_ALLDAY_ORIGINAL_EVENT_ID  =(CAL_PROPERTY_INSTANCE_ALLDAY|CAL_PROPERTY_DATA_TYPE_INT)+15,
	CAL_PROPERTY_INSTANCE_ALLDAY_LAST_MODIFIED_TIME =(CAL_PROPERTY_INSTANCE_ALLDAY|CAL_PROPERTY_DATA_TYPE_LLI)+16,

	CAL_PROPERTY_UPDATED_INFO_ID                =(CAL_PROPERTY_UPDATED_INFO|CAL_PROPERTY_DATA_TYPE_INT),
	CAL_PROPERTY_UPDATED_INFO_CALENDAR_ID       =(CAL_PROPERTY_UPDATED_INFO|CAL_PROPERTY_DATA_TYPE_INT)+1,
	CAL_PROPERTY_UPDATED_INFO_TYPE              =(CAL_PROPERTY_UPDATED_INFO|CAL_PROPERTY_DATA_TYPE_INT)+2,
	CAL_PROPERTY_UPDATED_INFO_VERSION           =(CAL_PROPERTY_UPDATED_INFO|CAL_PROPERTY_DATA_TYPE_INT)+3,

	CAL_PROPERTY_EXTENDED_ID                    =(CAL_PROPERTY_EXTENDED|CAL_PROPERTY_DATA_TYPE_INT|CAL_PROPERTY_FLAGS_READ_ONLY),
	CAL_PROPERTY_EXTENDED_RECORD_ID             =(CAL_PROPERTY_EXTENDED|CAL_PROPERTY_DATA_TYPE_INT)+1,
	CAL_PROPERTY_EXTENDED_RECORD_TYPE           =(CAL_PROPERTY_EXTENDED|CAL_PROPERTY_DATA_TYPE_INT)+2,
	CAL_PROPERTY_EXTENDED_KEY                   =(CAL_PROPERTY_EXTENDED|CAL_PROPERTY_DATA_TYPE_STR)+3,
	CAL_PROPERTY_EXTENDED_VALUE                 =(CAL_PROPERTY_EXTENDED|CAL_PROPERTY_DATA_TYPE_STR)+4,

} cal_property_ids_e;

void _cal_view_initialize(void);
cal_record_type_e _cal_view_get_type(const char *view_uri);
void _cal_view_finalize(void);

const cal_property_info_s* _cal_view_get_property_info(const char *view_uri, int *count);

const char* _cal_view_get_uri(const char *view_uri);

#endif /* __CALENDAR_SVC_VIEW_H__ */
