/*
 * Calendar Service
 *
 * Copyright (c) 2000 - 2012 Samsung Electronics Co., Ltd. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
#ifndef __CALENDAR_SVC_TZ_UTILS_H__
#define __CALENDAR_SVC_TZ_UTILS_H__

typedef struct _Time_Zone Time_Zone;
struct _Time_Zone
{
	char *city;
	char *country;
	char *gmt;
	char *tz_path;
};

static const Time_Zone time_zone_array[] =
{
{"Abidjan", "Ivory Coast", "GMT+0", "Africa/Abidjan"},
{"Abu Dhabi", "United Arab Emirates", "GMT+4", "Asia/Dubai"},
{"Accra", "Ghana", "GMT-10", "Africa/Accra"},
{"Addis Ababa", "Ethiopia", "GMT+3", "Africa/Addis_Ababa"},
{"Adelaide", "Australia", "GMT+9:30", "Australia/Adelaide"},
{"Alaska", "United States of America", "GMT-9", "America/Nome"},
{"Algiers", "Algeria", "GMT+1", "Africa/Algiers"},
{"Almaty", "Kazakhstan", "GMT+6", "Asia/Almaty"},
{"Ambon", "Indonesia", "GMT+1", "Asia/Jayapura"},
{"Amman", "Jordan", "GMT+2", "Asia/Amman"},
{"Amsterdam", "Netherlands", "GMT+1", "Europe/Amsterdam"},
{"Anadyr", "Russia ", "GMT+12", "Asia/Anadyr"},
{"Anchorage", "United States of America", "GMT-9", "America/Anchorage"},
{"Ankara", "Turkey", "GMT+2", "Asia/Istanbul"},
{"Antananarivo", "Madagascar", "GMT+3", "Indian/Antananarivo"},
{"Ashgabat", "Turkmenistan", "GMT+5", "Asia/Ashgabat"},
{"Asmera", "Eritrea", "GMT+3", "Africa/Asmara"  /* not in zone.tab */ },
{"Astana", "Kazakhstan", "GMT+6", "Asia/Almaty" /* not in zone.tab */ },
{"Asuncion", "Paraguay", "GMT-4", "America/Asuncion"},
{"Athens", "Greece", "GMT+2", "Europe/Athens"},
{"Auckland", "New Zealand", "GMT+12", "Pacific/Auckland"},
{"Austin", "United States of America", "GMT-6", "CST6CDT"},
{"Azores", "Portugal", "GMT-1", "Atlantic/Azores"},
{"Baghdad", "Iraq", "GMT+3", "Asia/Baghdad"},
{"Baku", "Azerbaijan", "GMT+4", "Asia/Baku"},
{"Baltimore", "United States of America", "GMT-5", "EST5EDT"},
{"Bamako", "Mali", "GMT+0", "Africa/Bamako"},
{"Bangkok", "Thailand", "GMT+7", "Asia/Bangkok"},
{"Bangui", "Central African Republic", "GMT+1", "Africa/Bangui"},
{"Barcelona", "Spain", "GMT+2", "Europe/Madrid"},
{"Bari", "Italy", "GMT+1", "Europe/Rome"},
{"Basse-Terre", "Guadeloupe", "GMT-4", "America/Guadeloupe"},
{"Beijing", "China", "GMT+8", "Asia/Shanghai"},
{"Beirut", "Lebanon", "GMT+2", "Asia/Beirut"},
{"Belgrade", "Serbia", "GMT+1", "Europe/Belgrade"},
{"Belize City", "Belize", "GMT-6", "America/Belize"},
{"Berlin", "Germany", "GMT+1", "Europe/Berlin"},
{"Bern", "Switzerland", "GMT+1", "Europe/Zurich"},
{"Bishkek", "Kyrgyzstan", "GMT+6", "Asia/Bishkek"},
{"Bissau", "Guinea Bissau", "GMT+0", "Africa/Bissau"},
{"Bogota", "Colombia", "GMT-5", "America/Bogota"},
{"Bologna", "Italy", "GMT+1", "Europe/Rome"},
{"Boston", "United States of America", "GMT-5", "EST5EDT"},
{"Brasilia", "Brazil", "GMT-3", "America/Sao_Paulo"},
{"Bratislava", "Slovakia", "GMT+2", "Europe/Bratislava"},
{"Bridgetown", "Barbados", "GMT-4", "America/Barbados"},
{"Brisbane", "Australia", "GMT+10", "Australia/Brisbane"},
{"Brussels", "Belgium", "GMT+1", "Europe/Brussels"},
{"Bucharest", "Romania", "GMT+3", "Europe/Bucharest"},
{"Budapest", "Hungary", "GMT+1", "Europe/Budapest"},
{"Buenos Aires", "Argentina", "GMT-3", "America/Argentina/Buenos_Aires"},
{"Cairo", "Egypt", "GMT+2", "Africa/Cairo"},
{"Calgary", "Canada", "GMT-7", "MST7MDT"},
{"Canary Islands", "Spain", "GMT+0", "Atlantic/Canary"},
{"Canberra", "Australia", "GMT+10", "Australia/Canberra"},
{"Canton", "China", "GMT+8", "Asia/Shanghai"},
{"Cape Town", "Republic of South Africa", "GMT+2", "Africa/Johannesburg"},
{"Caracas", "Venezuela", "GMT-4:30", "America/Caracas"},
{"Cardiff", "Wales", "GMT+0", "Europe/London"},
{"Casablanca", "Morocco", "GMT+0", "Africa/Casablanca"},
{"Catanzaro", "Italy", "GMT+1", "Europe/Rome"},
{"Cayenne", "French Guiana", "GMT-3", "America/Cayenne"},
{"Charlotte", "United States of America", "GMT-5", "EST5EDT"},
{"Charlotte Amalie", "United States Virgin Islands ", "GMT-5:30", "America/St_Thomas"},
{"Chelyabinsk", "Russia ", "GMT+5", "Asia/Yekaterinburg"},
{"Chennai", "India", "GMT+5:30", "Asia/Kolkata"},
{"Chicago", "United States of America", "GMT-6", "America/Chicago"},
{"Chisinau", "Moldova", "GMT+2", "Europe/Chisinau"},
{"Chita", "Russia", "GMT+9", "Asia/Yakutsk"},
{"Cleveland", "United States of America", "GMT-5", "EST5EDT"},
{"Colombo", "Sri Lanka", "GMT+5:30", "Asia/Colombo"},
{"Columbus", "United States of America", "GMT-5", "EST5EDT"},
{"Conakry", "Guinea", "GMT+1", "Africa/Conakry"},
{"Copenhagen", "Denmark", "GMT+1", "Europe/Copenhagen"},
{"Cork", "Ireland", "GMT+0", "Europe/Dublin"},
{"Crotone", "Italy", "GMT+1", "Europe/Rome"},
{"Dakar", "Senegal", "GMT+0", "Africa/Dakar"},
{"Dallas", "United States of America", "GMT-6", "CST6CDT"},
{"Damascus", "Syria", "GMT+2", "Asia/Damascus"},
{"Dar es Salaam", "Tanzania", "GMT+3", "Africa/Dar_es_Salaam"},
{"Darwin", "Australia", "GMT+9:30", "Australia/Darwin"},
{"Delhi", "India", "GMT+5:30", "Asia/Kolkata"},
{"Denpasar", "Indonesia", "GMT+8", "Asia/Makassar"},
{"Denver", "United States of America", "GMT-7", "America/Denver"},
{"Detroit", "United States of America", "GMT-5", "America/Detroit"},
{"Dhaka", "Bangladesh", "GMT+6", "Asia/Dhaka"},
{"Diego Garcia", "United Kingdom", "GMT+5", "Indian/Chagos" /* not in zone.tab */ },
{"Djibouti", "Djibouti", "GMT+3", "Africa/Djibouti"},
{"Doha", "Qatar", "GMT+3", "Asia/Qatar"},
{"Douala", "Cameroon", "GMT+1", "Africa/Douala"},
{"Dubai", "United Arab Emirates", "GMT+4", "Asia/Dubai"},
{"Dublin", "Ireland", "GMT+0", "Europe/Dublin"},
{"Dushanbe", "Tajikistan", "GMT+5", "Asia/Dushanbe"},
{"Easter Island", "Chile", "GMT-6", "Pacific/Easter"},
{"Edinburgh", "Scotland", "GMT+0", "Europe/London"},
{"El Paso", "United States of America", "GMT-7", "MST7MDT"},
{"Florence", "Italy", "GMT+1", "Europe/Rome"},
{"Fort-de-France", "Martinique", "GMT-4", "America/Martinique"},
{"Freetown", "Sierra Leone", "GMT+0", "Africa/Freetown"},
{"Gaborone", "Botswana", "GMT+2", "Africa/Gaborone"},
{"Galapagos Islands", "Ecuador", "GMT-7", "Pacific/Galapagos"},
{"Geneva", "Switzerland", "GMT+1", "Europe/Paris"},
{"Genoa", "Italy", "GMT+1", "Europe/Rome"},
{"Georgetown", "Guyana", "GMT-4", "America/Guyana"},
{"Grytviken", "South Georgia", "GMT-2", "Atlantic/South_Georgia"},
{"Guam", "United States of America", "GMT+10", "Pacific/Guam"},
{"Guatemala City", "Guatemala", "GMT-6", "America/Guatemala"},
{"Gustavia", "Saint Barthelemy", "GMT-4", "America/Antigua"},
{"Halifax", "Canada", "GMT-4", "America/Halifax"},
{"Hamburg", "Germany", "GMT+1", "Europe/Berlin"},
{"Hanoi", "Vietnam", "GMT+7", "Asia/Ho_Chi_Minh"},
{"Harare", "Zimbabwe", "GMT+2", "Africa/Harare"},
{"Havana", "Cuba", "GMT-5", "America/Havana"},
{"Hawaii", "United States of America", "GMT-10", "Pacific/Honolulu"},
{"Helsinki", "Finland", "GMT+2", "Europe/Helsinki"},
{"Hobart", "Australia", "GMT+10", "Australia/Hobart"},
{"Hong Kong", "China", "GMT+8", "Asia/Hong_Kong"},
{"Honolulu", "United States of America", "GMT-10", "Pacific/Honolulu"},
{"Houston", "United States of America", "GMT-6", "CST6CDT"},
{"Hovd", "Mongolia", "GMT+8", "Asia/Hovd"},
{"Indianapolis", "United States of America", "GMT-5", "America/Indiana/Indianapolis"},
{"Irkutsk", "Russia ", "GMT+8", "Asia/Irkutsk"},
{"Islamabad", "Pakistan", "GMT+5", "Asia/Karachi"},
{"Istanbul", "Turkey", "GMT+2", "Europe/Istanbul"},
{"Izhevsk", "Russia ", "GMT+4", "Europe/Moscow"},
{"Jakarta", "Indonesia", "GMT+7", "Asia/Jakarta"},
{"Jeddah", "Saudi Arabia", "GMT+3", "Asia/Riyadh"},
{"Jerusalem", "Israel", "GMT+2", "Asia/Jerusalem"},
{"Johannesburg", "South Africa", "GMT+2", "Africa/Johannesburg"},
{"Kabul", "Afghanistan", "GMT+4:30", "Asia/Kabul"},
{"Kaliningrad", "Russia", "GMT+2", "Europe/Kaliningrad"},
{"Kamchatka", "Russia ", "GMT+12", "Asia/Kamchatka"},
{"Kampala", "Uganda", "GMT+3", "Africa/Kampala"},
{"Karachi", "Pakistan", "GMT+5", "Asia/Karachi"},
{"Kathmandu", "Nepal", "GMT+5:45", "Asia/Kathmandu"},
{"Khabarovsk", "Russia ", "GMT+10", "Asia/Vladivostok"},
{"Kharkiv", "Ukraine", "GMT+2", "Europe/Kiev"},
{"Khartoum", "Sudan", "GMT+3", "Africa/Khartoum"},
{"Kiev", "Ukraine", "GMT+2", "Europe/Kiev"},
{"Kingston", "Canada", "GMT-5", "America/Toronto"}, /* not in zone.tab */
{"Kingston", "Jamaica", "GMT-5", "America/Jamaica"},
{"Kinshasa", "Democratic Republic of the Congo", "GMT+1", "Africa/Kinshasa"},
{"Kolkata", "India", "GMT+5:30", "Asia/Kolkata"},
{"Krasnoyarsk", "Russia ", "GMT+7", "Asia/Krasnoyarsk"},
{"Kuala Lumpur", "Malaysia", "GMT+8", "Asia/Kuala_Lumpur"},
{"Kuwait", "Kuwait", "GMT+3", "Asia/Kuwait"},
{"Kyiv", "Ukraine", "GMT+2", "Europe/Kiev" /* not in zone.tab */ },
{"Los Angeles", "United States of America", "GMT-7", "America/Los_Angeles"},
{"La Paz", "Bolivia", "GMT-4", "America/La_Paz"},
{"Lagos", "Nigeria", "GMT+1", "Africa/Lagos"},
{"Las Vegas", "United States of America", "GMT-8", "PST8PDT"},
{"Lima", "Peru", "GMT-5", "America/Lima"},
{"Lisbon", "Portugal", "GMT+0", "Europe/Lisbon"},
{"Ljubljana", "Slovakia", "GMT+1", "Europe/Ljubljana"},
{"London", "United Kingdom", "GMT+0", "Europe/London"},
{"Longhua", "China", "GMT+8", "Asia/Shanghai"},
{"Louisville", "United States of America", "GMT-5", "America/Kentucky/Louisville"},
{"Luanda", "Angola", "GMT+1", "Africa/Luanda"},
{"Lubumbashi", "Democratic Republic of the Congo", "GMT+2", "Africa/Lubumbashi"},
{"Lusaka", "Zambia", "GMT+2", "Africa/Lusaka"},
{"Luxembourg", "Luxembourg", "GMT+1", "Europe/Luxembourg"},
{"Lviv", "Ukraine", "GMT+2", "Europe/Kiev"},
{"Macau", "China", "GMT+8", "Asia/Macau"},
{"Madrid", "Spain", "GMT+2", "Europe/Madrid"},
{"Magadan", "Russia ", "GMT+11", "Asia/Magadan"},
{"Malabo", "Equaorial Guinea", "GMT+1", "Africa/Malabo"},
{"Male", "Maldives", "GMT+5", "Indian/Maldives"},
{"Managua", "Nicaragua", "GMT-6", "America/Managua"},
{"Manama", "Bahrain", "GMT+3", "Asia/Bahrain"},
{"Manila", "Philippines", "GMT+8", "Asia/Manila"},
{"Maputo", "Mozambique", "GMT+2", "Africa/Maputo"},
{"Marigot", "Saint Martin", "GMT-4", "America/Marigot"},
{"Mazatlan", "Mexico", "GMT-7", "America/Mazatlan"},
{"Mecca", "Saudi Arabia", "GMT+3", "Asia/Riyadh"},
{"Melbourne", "Australia", "GMT+10", "Australia/Melbourne"},
{"Memphis", "United States of America", "GMT-6", "CST6CDT"},
{"Messina", "Italy", "GMT+1", "Europe/Rome"},
{"Mexico City", "Mexico", "GMT-6", "America/Mexico_City"},
{"Miami", "United States of America", "GMT-5", "EST5EDT"},
{"Mid-Atlantic", "United States of America", "GMT-2", "America/New_York" /* not in zone.tab */ },
{"Midway Atoll", "United States of America", "GMT-11", "Pacific/Midway"},
{"Milan", "Italy", "GMT+1", "Europe/Rome"},
{"Milwaukee", "United States of America", "GMT-6", "CST6CDT"},
{"Minsk", "Belarus", "GMT+2", "Europe/Minsk"},
{"Mogadishu", "Somalia", "GMT+2", "Africa/Mogadishu"},
{"Monrovia", "Liberia", "GMT+0", "Africa/Monrovia"},
{"Montevideo", "Uruguay", "GMT-3", "America/Montevideo"},
{"Montreal", "Canada", "GMT-5", "America/Montreal"},
{"Moscow", "Russia ", "GMT+3", "Europe/Moscow"},
{"Mumbai", "India", "GMT+5:30", "Asia/Kolkata"},
{"Munich", "Germany", "GMT+1", "Europe/Berlin"},
{"Muscat", "Oman", "GMT+4", "Asia/Muscat"},
{"Nairobi", "Kenya", "GMT+3", "Africa/Nairobi"},
{"Naples", "Italy", "GMT+1", "Europe/Rome"},
{"Naters", "Switzerland", "GMT+1", "Europe/Zurich"},
{"Ndjamena", "Chad", "GMT+1", "Africa/Ndjamena"},
{"New Delhi", "India", "GMT+5:30", "Asia/Kolkata" /* not in zone.tab */ },
{"New York", "United States of America", "GMT-4", "America/New_York"},
{"Newfoundland", "Canada", "GMT-3:30", "America/St_Johns"},
{"Niamey", "Niger", "GMT+1", "Africa/Niamey"},
{"Nouakchott", "Mauritania", "GMT+1", "Africa/Nouakchott"},
{"Noumea", "New Caledonia", "GMT+11", "Pacific/Noumea"},
{"Novokuznetsk", "Russia", "GMT+7", "Asia/Novokuznetsk"},
{"Novosibirsk", "Russia", "GMT+6", "Asia/Novosibirsk"},
{"Nuku'alofa", "Tonga", "GMT+13", "Pacific/Tongatapu"},
{"Nuuk", "Greenland", "GMT-3", "America/Godthab"},
{"Omsk", "Russia", "GMT+6", "Asia/Omsk"},
{"Osaka", "Japan", "GMT+9", "Asia/Tokyo"},
{"Ottawa", "Canada", "GMT-5", "EST5EDT"},
{"Ouagadougou", "Burkina Faso", "GMT+0", "Africa/Ouagadougou"},
{"Pago Pago", "Independent State of Samoa", "GMT-11", "Pacific/Pago_Pago"},
{"Palermo", "Italy", "GMT+1", "Europe/Rome"},
{"Panama City", "Panama", "GMT-6", "America/Panama"},
{"Paramaribo", "Surinam", "GMT-3", "America/Paramaribo"},
{"Paris", "France", "GMT+1", "Europe/Paris"},
{"Perm", "Russia", "GMT+5", "Asia/Yekaterinburg"},
{"Perth", "Australia", "GMT+8", "Australia/Perth"},
{"Petropavlovsk-Kamchatskiy", "Russia ", "GMT+12", "Asia/Kamchatka"},
{"Philadelphia", "United States of America", "GMT-5", "EST5EDT"},
{"Phnom Penh ", "Cambodia", "GMT-5", "Asia/Phnom_Penh"},
{"Phoenix", "United States of America", "GMT-7", "America/Phoenix"},
{"Podgorica", "Montenegro", "GMT+1", "Europe/Podgorica"},
{"Ponta Delgada", "Portugal", "GMT-1", "Atlantic/Azores"},
{"Port Louis", "Mauritius", "GMT+4", "Indian/Mauritius"},
{"Port-au-Prince", "Haiti", "GMT-5", "America/Port-au-Prince"},
{"Portland", "United States of America", "GMT-8", "PST8PDT"},
{"Prague", "Czech Republic", "GMT+1", "Europe/Prague"},
{"Pyongyang", "North Korea", "GMT+9", "Asia/Pyongyang"},
{"Quito", "Ecuador", "GMT-5", "America/Guayaquil"},
{"Rabat", "Morocco", "GMT+0", "Africa/Casablanca"},
{"Rangoon", "Burma", "GMT+6:30", "Asia/Rangoon"},
{"Recife", "Brazil", "GMT-3", "America/Recife"},
{"Regina", "Canada", "GMT-6", "America/Regina"},
{"Reykjavik", "Iceland", "GMT+0", "Atlantic/Reykjavik"},
{"Riga", "Latvia", "GMT+2", "Europe/Riga"},
{"Rio de Janeiro", "Brazil", "GMT-2", "America/Sao_Paulo"},
{"Riyadh", "Saudi Arabia", "GMT+3", "Asia/Riyadh"},
{"Rome", "Italy", "GMT+1", "Europe/Rome"},
{"Saint-Denis", "Reunion Island", "GMT+4", "Indian/Reunion"},
{"Samara", "Russia ", "GMT+4", "Europe/Samara"},
{"San Antonio", "United States of America", "GMT-6", "CST6CDT"},
{"San Diego", "United States of America", "GMT-8", "PST8PDT"},
{"San Francisco", "United States of America", "GMT-8", "America/Los_Angeles"},
{"San Jose", "United States of America", "GMT-8", "PST8PDT"},
{"San Jose", "Costa Rica", "GMT-6", "America/Costa_Rica"},
{"San Juan", "Puerto Rico", "GMT-4", "America/Puerto_Rico"},
{"San Marino", "Italy", "GMT+1", "Europe/San_Marino"},
{"San Salvador", "El Salvador", "GMT-6", "America/El_Salvador"},
{"Sanaa", "Yemen", "GMT+3", "Asia/Aden"  /* not in zone.tab */ },
{"Santiago", "Chile", "GMT-4", "America/Santiago"},
{"Santo Domingo", "Dominican Republic", "GMT-4", "America/Santo_Domingo"},
{"Sao Paulo", "Brazil", "GMT-2", "America/Sao_Paulo"},
{"Seattle", "United States of America", "GMT-8", "PST8PDT"},
{"Seoul", "Republic of Korea", "GMT+9", "Asia/Seoul"},
{"Shanghai", "China", "GMT+8", "Asia/Shanghai"},
{"Shenzhen", "China", "GMT+8", "Asia/Shanghai"},
{"Singapore", "Republic of Singapore", "GMT+8", "Asia/Singapore"},
{"Skopje", "Macedonia", "GMT+1", "Europe/Skopje"},
{"Sofia ", "Bulgaria", "GMT+3", "Europe/Sofia"},
{"St. John's", "Antigua and Barbuda", "GMT-4", "America/Antigua"},
{"St. John's", "Canada", "GMT-3:30", "America/St_Johns"},
{"St. Petersburg", "Russia", "GMT+3", "Europe/Moscow"},
{"Stockholm", "Sweden", "GMT+2", "Europe/Stockholm"},
{"Suva", "Fiji", "GMT+12", "Pacific/Fiji"},
{"Sydney", "Australia", "GMT+11", "Australia/Sydney"},
{"Tahiti", "French Polynesia", "GMT-10", "Pacific/Tahiti"},
{"Taipei", "Taiwan", "GMT+8", "Asia/Taipei"},
{"Tallinn", "Estonia", "GMT+2", "Europe/Tallinn"},
{"Tarawa", "Kiribati", "GMT+12", "Pacific/Tarawa"},
{"Tashkent", "Uzbekistan", "GMT+5", "Asia/Tashkent"},
{"Tbilisi", "Georgia", "GMT+4", "Asia/Tbilisi"},
{"Tegucigalpa", "Honduras", "GMT-6", "America/Tegucigalpa"},
{"Tehran", "Iran", "GMT+3:30", "Asia/Tehran"},
{"Thanh Pho Ho Chi Minh", "Vietnam", "GMT+7", "Asia/Ho_Chi_Minh"},
{"The Settlement", "British Virgin Islands ", "GMT-4", "America/Tortola"},
{"Tientsin", "China", "GMT+8", "Asia/Shanghai" /* not in zone.tab */ },
{"Tijuana", "Mexico", "GMT-5", "America/Tijuana"},
{"Tokyo", "Japan", "GMT+9", "Asia/Tokyo"},
{"Toronto", "Canada", "GMT-4", "America/Toronto"},
{"Trehet", "France", "GMT+1", "Europe/Paris" /* not in zone.tab */ },
{"Tripoli", "Libya", "GMT+2", "Africa/Tripoli"},
{"Tunis", "Tunisia", "GMT+2", "Africa/Tunis"},
{"Turin", "Italy", "GMT+1", "Europe/Rome"},
{"Ufa", "Bashkiriya", "GMT+5", "Asia/Yekaterinburg"},
{"Ulan Bator", "Mongolia", "GMT+8", "Asia/Ulan_Bator"},
{"Vaduz", "Liechtenstein", "GMT+1", "Europe/Vaduz"},
{"Valletta", "Malta", "GMT+1", "Europe/Malta"},
{"Vancouver", "Canada", "GMT-8", "America/Vancouver"},
{"Verona", "Italy", "GMT+1", "Europe/Rome"},
{"Victoria", "Seychelles", "GMT+4", "Australia/Melbourne"},
{"Vienna", "Austria", "GMT+1", "Europe/Vienna"},
{"Vilnius", "Lithuania", "GMT+3", "Europe/Vilnius"},
{"Vladivostok", "Russia ", "GMT+10", "Asia/Vladivostok"},
{"Volgograd", "Russia ", "GMT+4", "Europe/Volgograd"},
{"Warsaw", "Poland", "GMT+2", "Europe/Warsaw"},
{"Washington, D.C.", "United States of America", "GMT-5", "EST5EDT"},
{"Wellington", "New Zealand", "GMT+12", "Pacific/Auckland"},
{"Winnipeg", "Canada", "GMT-5", "America/Winnipeg"},
{"Yakutsk", "Russia ", "GMT+9", "Asia/Yakutsk"},
{"Yamoussoukro", "Ivory Coast", "GMT+0", "Africa/Abidjan"},
{"Yaounde", "Cameroon", "GMT+1", "Africa/Douala" /* not in zone.tab */ },
{"Yekaterinburg", "Russia ", "GMT+5", "Asia/Yekaterinburg"},
{"Yerevan", "Armenia", "GMT+5", "Asia/Yerevan"},
{"Yuzhno-Sakhalinsk", "Russia ", "GMT+11", "Asia/Sakhalin"},
{"Zagreb", "Croatia", "GMT+1", "Europe/Zagreb"},
{"Zurich", "Switzerland", "GMT+1", "Europe/Zurich"},
{NULL, NULL, NULL, NULL}
};

static const Time_Zone tz_path_array[] =
{
{"Abidjan","Ivory Coast","GMT+0","Africa/Abidjan"},
{"Yamoussoukro","Ivory Coast","GMT+0","Africa/Abidjan"},
{"Accra","Ghana","GMT-10","Africa/Accra"},
{"Addis Ababa","Ethiopia","GMT+3","Africa/Addis_Ababa"},
{"Algiers","Algeria","GMT+1","Africa/Algiers"},
{"Asmera","Eritrea","GMT+3","Africa/Asmara "},
{"Bamako","Mali","GMT+0","Africa/Bamako"},
{"Bangui","Central African Republic","GMT+1","Africa/Bangui"},
{"Bissau","Guinea Bissau","GMT+0","Africa/Bissau"},
{"Cairo","Egypt","GMT+2","Africa/Cairo"},
{"Casablanca","Morocco","GMT+0","Africa/Casablanca"},
{"Rabat","Morocco","GMT+0","Africa/Casablanca"},
{"Conakry","Guinea","GMT+1","Africa/Conakry"},
{"Dakar","Senegal","GMT+0","Africa/Dakar"},
{"Dar es Salaam","Tanzania","GMT+3","Africa/Dar_es_Salaam"},
{"Djibouti","Djibouti","GMT+3","Africa/Djibouti"},
{"Douala","Cameroon","GMT+1","Africa/Douala"},
{"Yaounde","Cameroon","GMT+1","Africa/Douala "},
{"Freetown","Sierra Leone","GMT+0","Africa/Freetown"},
{"Gaborone","Botswana","GMT+2","Africa/Gaborone"},
{"Harare","Zimbabwe","GMT+2","Africa/Harare"},
{"Cape Town","Republic of South Africa","GMT+2","Africa/Johannesburg"},
{"Johannesburg","South Africa","GMT+2","Africa/Johannesburg"},
{"Kampala","Uganda","GMT+3","Africa/Kampala"},
{"Khartoum","Sudan","GMT+3","Africa/Khartoum"},
{"Kinshasa","Democratic Republic of the Congo","GMT+1","Africa/Kinshasa"},
{"Lagos","Nigeria","GMT+1","Africa/Lagos"},
{"Luanda","Angola","GMT+1","Africa/Luanda"},
{"Lubumbashi","Democratic Republic of the Congo","GMT+2","Africa/Lubumbashi"},
{"Lusaka","Zambia","GMT+2","Africa/Lusaka"},
{"Malabo","Equaorial Guinea","GMT+1","Africa/Malabo"},
{"Maputo","Mozambique","GMT+2","Africa/Maputo"},
{"Mogadishu","Somalia","GMT+2","Africa/Mogadishu"},
{"Monrovia","Liberia","GMT+0","Africa/Monrovia"},
{"Nairobi","Kenya","GMT+3","Africa/Nairobi"},
{"Ndjamena","Chad","GMT+1","Africa/Ndjamena"},
{"Niamey","Niger","GMT+1","Africa/Niamey"},
{"Nouakchott","Mauritania","GMT+1","Africa/Nouakchott"},
{"Ouagadougou","Burkina Faso","GMT+0","Africa/Ouagadougou"},
{"Tripoli","Libya","GMT+2","Africa/Tripoli"},
{"Tunis","Tunisia","GMT+2","Africa/Tunis"},
{"Anchorage","United States of America","GMT-9","America/Anchorage"},
{"Gustavia","Saint Barthelemy","GMT-4","America/Antigua"},
{"St. John's","Antigua and Barbuda","GMT-4","America/Antigua"},
{"Buenos Aires","Argentina","GMT-3","America/Argentina/Buenos_Aires"},
{"Asuncion","Paraguay","GMT-4","America/Asuncion"},
{"Bridgetown","Barbados","GMT-4","America/Barbados"},
{"Belize City","Belize","GMT-6","America/Belize"},
{"Bogota","Colombia","GMT-5","America/Bogota"},
{"Caracas","Venezuela","GMT-4:30","America/Caracas"},
{"Cayenne","French Guiana","GMT-3","America/Cayenne"},
{"Chicago","United States of America","GMT-6","America/Chicago"},
{"San Jose","Costa Rica","GMT-6","America/Costa_Rica"},
{"Denver","United States of America","GMT-7","America/Denver"},
{"Detroit","United States of America","GMT-5","America/Detroit"},
{"San Salvador","El Salvador","GMT-6","America/El_Salvador"},
{"Nuuk","Greenland","GMT-3","America/Godthab"},
{"Basse-Terre","Guadeloupe","GMT-4","America/Guadeloupe"},
{"Guatemala City","Guatemala","GMT-6","America/Guatemala"},
{"Quito","Ecuador","GMT-5","America/Guayaquil"},
{"Georgetown","Guyana","GMT-4","America/Guyana"},
{"Halifax","Canada","GMT-4","America/Halifax"},
{"Havana","Cuba","GMT-5","America/Havana"},
{"Indianapolis","United States of America","GMT-5","America/Indiana/Indianapolis"},
{"Kingston","Jamaica","GMT-5","America/Jamaica"},
{"Louisville","United States of America","GMT-5","America/Kentucky/Louisville"},
{"La Paz","Bolivia","GMT-4","America/La_Paz"},
{"Lima","Peru","GMT-5","America/Lima"},
{"Los Angeles","United States of America","GMT-7","America/Los_Angeles"},
{"San Francisco","United States of America","GMT-8","America/Los_Angeles"},
{"Managua","Nicaragua","GMT-6","America/Managua"},
{"Marigot","Saint Martin","GMT-4","America/Marigot"},
{"Fort-de-France","Martinique","GMT-4","America/Martinique"},
{"Mazatlan","Mexico","GMT-7","America/Mazatlan"},
{"Mexico City","Mexico","GMT-6","America/Mexico_City"},
{"Montevideo","Uruguay","GMT-3","America/Montevideo"},
{"Montreal","Canada","GMT-5","America/Montreal"},
{"New York","United States of America","GMT-4","America/New_York"},
{"Mid-Atlantic","United States of America","GMT-2","America/New_York "},
{"Alaska","United States of America","GMT-9","America/Nome"},
{"Panama City","Panama","GMT-6","America/Panama"},
{"Paramaribo","Surinam","GMT-3","America/Paramaribo"},
{"Phoenix","United States of America","GMT-7","America/Phoenix"},
{"Port-au-Prince","Haiti","GMT-5","America/Port-au-Prince"},
{"San Juan","Puerto Rico","GMT-4","America/Puerto_Rico"},
{"Recife","Brazil","GMT-3","America/Recife"},
{"Regina","Canada","GMT-6","America/Regina"},
{"Santiago","Chile","GMT-4","America/Santiago"},
{"Santo Domingo","Dominican Republic","GMT-4","America/Santo_Domingo"},
{"Brasilia","Brazil","GMT-3","America/Sao_Paulo"},
{"Rio de Janeiro","Brazil","GMT-2","America/Sao_Paulo"},
{"Sao Paulo","Brazil","GMT-2","America/Sao_Paulo"},
{"Newfoundland","Canada","GMT-3:30","America/St_Johns"},
{"St. John's","Canada","GMT-3:30","America/St_Johns"},
{"Charlotte Amalie","United States Virgin Islands ","GMT-5:30","America/St_Thomas"},
{"Tegucigalpa","Honduras","GMT-6","America/Tegucigalpa"},
{"Tijuana","Mexico","GMT-5","America/Tijuana"},
{"Toronto","Canada","GMT-4","America/Toronto"},
{"Kingston","Canada","GMT-5","America/Toronto "},
{"The Settlement","British Virgin Islands ","GMT-4","America/Tortola"},
{"Vancouver","Canada","GMT-8","America/Vancouver"},
{"Winnipeg","Canada","GMT-5","America/Winnipeg"},
{"Sanaa","Yemen","GMT+3","Asia/Aden "},
{"Almaty","Kazakhstan","GMT+6","Asia/Almaty"},
{"Astana","Kazakhstan","GMT+6","Asia/Almaty "},
{"Amman","Jordan","GMT+2","Asia/Amman"},
{"Anadyr","Russia","GMT+12","Asia/Anadyr"},
{"Ashgabat","Turkmenistan","GMT+5","Asia/Ashgabat"},
{"Baghdad","Iraq","GMT+3","Asia/Baghdad"},
{"Manama","Bahrain","GMT+3","Asia/Bahrain"},
{"Baku","Azerbaijan","GMT+4","Asia/Baku"},
{"Bangkok","Thailand","GMT+7","Asia/Bangkok"},
{"Beirut","Lebanon","GMT+2","Asia/Beirut"},
{"Bishkek","Kyrgyzstan","GMT+6","Asia/Bishkek"},
{"Colombo","Sri Lanka","GMT+5:30","Asia/Colombo"},
{"Damascus","Syria","GMT+2","Asia/Damascus"},
{"Dhaka","Bangladesh","GMT+6","Asia/Dhaka"},
{"Abu Dhabi","United Arab Emirates","GMT+4","Asia/Dubai"},
{"Dubai","United Arab Emirates","GMT+4","Asia/Dubai"},
{"Dushanbe","Tajikistan","GMT+5","Asia/Dushanbe"},
{"Hanoi","Vietnam","GMT+7","Asia/Ho_Chi_Minh"},
{"Thanh Pho Ho Chi Minh","Vietnam","GMT+7","Asia/Ho_Chi_Minh"},
{"Hong Kong","China","GMT+8","Asia/Hong_Kong"},
{"Hovd","Mongolia","GMT+8","Asia/Hovd"},
{"Irkutsk","Russia","GMT+8","Asia/Irkutsk"},
{"Ankara","Turkey","GMT+2","Asia/Istanbul"},
{"Jakarta","Indonesia","GMT+7","Asia/Jakarta"},
{"Ambon","Indonesia","GMT+1","Asia/Jayapura"},
{"Jerusalem","Israel","GMT+2","Asia/Jerusalem"},
{"Kabul","Afghanistan","GMT+4:30","Asia/Kabul"},
{"Kamchatka","Russia ","GMT+12","Asia/Kamchatka"},
{"Petropavlovsk-Kamchatskiy","Russia ","GMT+12","Asia/Kamchatka"},
{"Islamabad","Pakistan","GMT+5","Asia/Karachi"},
{"Karachi","Pakistan","GMT+5","Asia/Karachi"},
{"Kathmandu","Nepal","GMT+5:45","Asia/Kathmandu"},
{"Chennai","India","GMT+5:30","Asia/Kolkata"},
{"Delhi","India","GMT+5:30","Asia/Kolkata"},
{"Kolkata","India","GMT+5:30","Asia/Kolkata"},
{"Mumbai","India","GMT+5:30","Asia/Kolkata"},
{"New Delhi","India","GMT+5:30","Asia/Kolkata "},
{"Krasnoyarsk","Russia","GMT+7","Asia/Krasnoyarsk"},
{"Kuala Lumpur","Malaysia","GMT+8","Asia/Kuala_Lumpur"},
{"Kuwait","Kuwait","GMT+3","Asia/Kuwait"},
{"Macau","China","GMT+8","Asia/Macau"},
{"Magadan","Russia","GMT+11","Asia/Magadan"},
{"Denpasar","Indonesia","GMT+8","Asia/Makassar"},
{"Manila","Philippines","GMT+8","Asia/Manila"},
{"Muscat","Oman","GMT+4","Asia/Muscat"},
{"Novokuznetsk","Russia","GMT+7","Asia/Novokuznetsk"},
{"Novosibirsk","Russia","GMT+6","Asia/Novosibirsk"},
{"Omsk","Russia","GMT+6","Asia/Omsk"},
{"Phnom Penh ","Cambodia","GMT-5","Asia/Phnom_Penh"},
{"Pyongyang","North Korea","GMT+9","Asia/Pyongyang"},
{"Doha","Qatar","GMT+3","Asia/Qatar"},
{"Rangoon","Burma","GMT+6:30","Asia/Rangoon"},
{"Jeddah","Saudi Arabia","GMT+3","Asia/Riyadh"},
{"Mecca","Saudi Arabia","GMT+3","Asia/Riyadh"},
{"Riyadh","Saudi Arabia","GMT+3","Asia/Riyadh"},
{"Yuzhno-Sakhalinsk","Russia","GMT+11","Asia/Sakhalin"},
{"Seoul","Republic of Korea","GMT+9","Asia/Seoul"},
{"Beijing","China","GMT+8","Asia/Shanghai"},
{"Canton","China","GMT+8","Asia/Shanghai"},
{"Longhua","China","GMT+8","Asia/Shanghai"},
{"Shanghai","China","GMT+8","Asia/Shanghai"},
{"Shenzhen","China","GMT+8","Asia/Shanghai"},
{"Tientsin","China","GMT+8","Asia/Shanghai "},
{"Singapore","Republic of Singapore","GMT+8","Asia/Singapore"},
{"Taipei","Taiwan","GMT+8","Asia/Taipei"},
{"Tashkent","Uzbekistan","GMT+5","Asia/Tashkent"},
{"Tbilisi","Georgia","GMT+4","Asia/Tbilisi"},
{"Tehran","Iran","GMT+3:30","Asia/Tehran"},
{"Osaka","Japan","GMT+9","Asia/Tokyo"},
{"Tokyo","Japan","GMT+9","Asia/Tokyo"},
{"Ulan Bator","Mongolia","GMT+8","Asia/Ulan_Bator"},
{"Khabarovsk","Russia","GMT+10","Asia/Vladivostok"},
{"Vladivostok","Russia","GMT+10","Asia/Vladivostok"},
{"Chita","Russia","GMT+9","Asia/Yakutsk"},
{"Yakutsk","Russia","GMT+9","Asia/Yakutsk"},
{"Chelyabinsk","Russia","GMT+5","Asia/Yekaterinburg"},
{"Perm","Russia","GMT+5","Asia/Yekaterinburg"},
{"Ufa","Bashkiriya","GMT+5","Asia/Yekaterinburg"},
{"Yekaterinburg","Russia","GMT+5","Asia/Yekaterinburg"},
{"Yerevan","Armenia","GMT+5","Asia/Yerevan"},
{"Azores","Portugal","GMT-1","Atlantic/Azores"},
{"Ponta Delgada","Portugal","GMT-1","Atlantic/Azores"},
{"Canary Islands","Spain","GMT+0","Atlantic/Canary"},
{"Reykjavik","Iceland","GMT+0","Atlantic/Reykjavik"},
{"Grytviken","South Georgia","GMT-2","Atlantic/South_Georgia"},
{"Adelaide","Australia","GMT+9:30","Australia/Adelaide"},
{"Brisbane","Australia","GMT+10","Australia/Brisbane"},
{"Canberra","Australia","GMT+10","Australia/Canberra"},
{"Darwin","Australia","GMT+9:30","Australia/Darwin"},
{"Hobart","Australia","GMT+10","Australia/Hobart"},
{"Melbourne","Australia","GMT+10","Australia/Melbourne"},
{"Victoria","Seychelles","GMT+4","Australia/Melbourne"},
{"Perth","Australia","GMT+8","Australia/Perth"},
{"Sydney","Australia","GMT+11","Australia/Sydney"},
{"Austin","United States of America","GMT-6","CST6CDT"},
{"Dallas","United States of America","GMT-6","CST6CDT"},
{"Houston","United States of America","GMT-6","CST6CDT"},
{"Memphis","United States of America","GMT-6","CST6CDT"},
{"Milwaukee","United States of America","GMT-6","CST6CDT"},
{"San Antonio","United States of America","GMT-6","CST6CDT"},
{"Baltimore","United States of America","GMT-5","EST5EDT"},
{"Boston","United States of America","GMT-5","EST5EDT"},
{"Charlotte","United States of America","GMT-5","EST5EDT"},
{"Cleveland","United States of America","GMT-5","EST5EDT"},
{"Columbus","United States of America","GMT-5","EST5EDT"},
{"Miami","United States of America","GMT-5","EST5EDT"},
{"Ottawa","Canada","GMT-5","EST5EDT"},
{"Philadelphia","United States of America","GMT-5","EST5EDT"},
{"Amsterdam","Netherlands","GMT+1","Europe/Amsterdam"},
{"Athens","Greece","GMT+2","Europe/Athens"},
{"Belgrade","Serbia","GMT+1","Europe/Belgrade"},
{"Berlin","Germany","GMT+1","Europe/Berlin"},
{"Hamburg","Germany","GMT+1","Europe/Berlin"},
{"Munich","Germany","GMT+1","Europe/Berlin"},
{"Bratislava","Slovakia","GMT+2","Europe/Bratislava"},
{"Brussels","Belgium","GMT+1","Europe/Brussels"},
{"Bucharest","Romania","GMT+3","Europe/Bucharest"},
{"Budapest","Hungary","GMT+1","Europe/Budapest"},
{"Chisinau","Moldova","GMT+2","Europe/Chisinau"},
{"Copenhagen","Denmark","GMT+1","Europe/Copenhagen"},
{"Cork","Ireland","GMT+0","Europe/Dublin"},
{"Dublin","Ireland","GMT+0","Europe/Dublin"},
{"Helsinki","Finland","GMT+2","Europe/Helsinki"},
{"Istanbul","Turkey","GMT+2","Europe/Istanbul"},
{"Kaliningrad","Russia","GMT+2","Europe/Kaliningrad"},
{"Kharkiv","Ukraine","GMT+2","Europe/Kiev"},
{"Kiev","Ukraine","GMT+2","Europe/Kiev"},
{"Lviv","Ukraine","GMT+2","Europe/Kiev"},
{"Kyiv","Ukraine","GMT+2","Europe/Kiev "},
{"Lisbon","Portugal","GMT+0","Europe/Lisbon"},
{"Ljubljana","Slovakia","GMT+1","Europe/Ljubljana"},
{"Cardiff","Wales","GMT+0","Europe/London"},
{"Edinburgh","Scotland","GMT+0","Europe/London"},
{"London","United Kingdom","GMT+0","Europe/London"},
{"Luxembourg","Luxembourg","GMT+1","Europe/Luxembourg"},
{"Barcelona","Spain","GMT+2","Europe/Madrid"},
{"Madrid","Spain","GMT+2","Europe/Madrid"},
{"Valletta","Malta","GMT+1","Europe/Malta"},
{"Minsk","Belarus","GMT+2","Europe/Minsk"},
{"Izhevsk","Russia","GMT+4","Europe/Moscow"},
{"Moscow","Russia","GMT+3","Europe/Moscow"},
{"St. Petersburg","Russia","GMT+3","Europe/Moscow"},
{"Geneva","Switzerland","GMT+1","Europe/Paris"},
{"Paris","France","GMT+1","Europe/Paris"},
{"Trehet","France","GMT+1","Europe/Paris "},
{"Podgorica","Montenegro","GMT+1","Europe/Podgorica"},
{"Prague","Czech Republic","GMT+1","Europe/Prague"},
{"Riga","Latvia","GMT+2","Europe/Riga"},
{"Bari","Italy","GMT+1","Europe/Rome"},
{"Bologna","Italy","GMT+1","Europe/Rome"},
{"Catanzaro","Italy","GMT+1","Europe/Rome"},
{"Crotone","Italy","GMT+1","Europe/Rome"},
{"Florence","Italy","GMT+1","Europe/Rome"},
{"Genoa","Italy","GMT+1","Europe/Rome"},
{"Messina","Italy","GMT+1","Europe/Rome"},
{"Milan","Italy","GMT+1","Europe/Rome"},
{"Naples","Italy","GMT+1","Europe/Rome"},
{"Palermo","Italy","GMT+1","Europe/Rome"},
{"Rome","Italy","GMT+1","Europe/Rome"},
{"Turin","Italy","GMT+1","Europe/Rome"},
{"Verona","Italy","GMT+1","Europe/Rome"},
{"Samara","Russia","GMT+4","Europe/Samara"},
{"San Marino","Italy","GMT+1","Europe/San_Marino"},
{"Skopje","Macedonia","GMT+1","Europe/Skopje"},
{"Sofia ","Bulgaria","GMT+3","Europe/Sofia"},
{"Stockholm","Sweden","GMT+2","Europe/Stockholm"},
{"Tallinn","Estonia","GMT+2","Europe/Tallinn"},
{"Vaduz","Liechtenstein","GMT+1","Europe/Vaduz"},
{"Vienna","Austria","GMT+1","Europe/Vienna"},
{"Vilnius","Lithuania","GMT+3","Europe/Vilnius"},
{"Volgograd","Russia","GMT+4","Europe/Volgograd"},
{"Warsaw","Poland","GMT+2","Europe/Warsaw"},
{"Zagreb","Croatia","GMT+1","Europe/Zagreb"},
{"Bern","Switzerland","GMT+1","Europe/Zurich"},
{"Naters","Switzerland","GMT+1","Europe/Zurich"},
{"Zurich","Switzerland","GMT+1","Europe/Zurich"},
{"Antananarivo","Madagascar","GMT+3","Indian/Antananarivo"},
{"Diego Garcia","United Kingdom","GMT+5","Indian/Chagos "},
{"Male","Maldives","GMT+5","Indian/Maldives"},
{"Port Louis","Mauritius","GMT+4","Indian/Mauritius"},
{"Saint-Denis","Reunion Island","GMT+4","Indian/Reunion"},
{"Calgary","Canada","GMT-7","MST7MDT"},
{"El Paso","United States of America","GMT-7","MST7MDT"},
{"Auckland","New Zealand","GMT+12","Pacific/Auckland"},
{"Wellington","New Zealand","GMT+12","Pacific/Auckland"},
{"Easter Island","Chile","GMT-6","Pacific/Easter"},
{"Suva","Fiji","GMT+12","Pacific/Fiji"},
{"Galapagos Islands","Ecuador","GMT-7","Pacific/Galapagos"},
{"Guam","United States of America","GMT+10","Pacific/Guam"},
{"Hawaii","United States of America","GMT-10","Pacific/Honolulu"},
{"Honolulu","United States of America","GMT-10","Pacific/Honolulu"},
{"Midway Atoll","United States of America","GMT-11","Pacific/Midway"},
{"Noumea","New Caledonia","GMT+11","Pacific/Noumea"},
{"Pago Pago","Independent State of Samoa","GMT-11","Pacific/Pago_Pago"},
{"Tahiti","French Polynesia","GMT-10","Pacific/Tahiti"},
{"Tarawa","Kiribati","GMT+12","Pacific/Tarawa"},
{"Nuku'alofa","Tonga","GMT+13","Pacific/Tongatapu"},
{"Las Vegas","United States of America","GMT-8","PST8PDT"},
{"Portland","United States of America","GMT-8","PST8PDT"},
{"San Diego","United States of America","GMT-8","PST8PDT"},
{"San Jose","United States of America","GMT-8","PST8PDT"},
{"Seattle","United States of America","GMT-8","PST8PDT"},
{"Washington, D.C.","United States of America","GMT-5","EST5EDT"},
{NULL, NULL, NULL, NULL}
};

#ifndef SECSPERHOUR
#define SECSPERHOUR	3600 //(SECSPERMIN * MINSPERHOUR)
#endif /* !defined SECSPERHOUR */

#ifndef SECSPERDAY
#define SECSPERDAY	86400 //(SECSPERHOUR * HOURSPERDAY)
#endif /* !defined SECSPERDAY */


time_t cals_mktime(struct tm *date_time);
struct tm *cals_tmtime(time_t *sec);
struct tm* cals_tmtime_r(time_t *ttTime, struct tm *tmTime);

#endif /* __CALENDAR_SVC_TZ_UTILS_H__ */
